### PR TITLE
Abstract Arguments Parser & Add File Watcher

### PR DESCRIPTION
**Pull request by s0kil**
It's beneficial for maintainability to use a small lib to parse the args

### CODE REVIEW

**Comment by ts-thomas** [comment]
Wow, nice one :)

**Comment by ts-thomas** [comment]
Would be nice if we can provide single-dash also:
```cmd
npx mikado-compile -src ./template.html -dest dist/ -type json
```
```cmd
npx mikado-compile -s ./template.html -d dist/ -t json -f -p
```
The old method has covered this :)

**Comment by ts-thomas** [comment]
The watcher is really nice. We need to have the flag `force` to be _false_ by default. Just when running the watcher this option should be _true_ by default.

**Comment by ts-thomas** [comment]
The package "totalist" is pretty new and redundant with the package "glob". But let us try this newer one and drop "glob".

**Comment by ts-thomas** [comment]
Also "pretty" should be _false_ by default, because both "pretty" and "force" are "positive flags", they could just be used to enable something :)

**Comment by s0kil** [comment]
> Would be nice if we can provide single-dash also:
> 
> ```batchfile
> npx mikado-compile -src ./template.html -dest dist/ -type json
> ```
> 
> ```batchfile
> npx mikado-compile -s ./template.html -d dist/ -t json -f -p
> ```
> 
> The old method has covered this :)

This does work

**Comment by ts-thomas** [comment]
Oh sorry, my fault. I will try it again :)

**Pull request merged**
