### PR TITLE
Fix template path

### PR DESCRIPTION
**Pull request by s0kil**

### CODE REVIEW

**Comment by ts-thomas** [comment]
Sorry I did not recognize this PR. Do you like to reopen?

**Comment by s0kil** [comment]
My goal was to be able to use the compiler as a library and CLI, so It would be easier to implement bundler(Rollup, Webpack) plugins, and also a file watcher that compiles templates when they change.

Is that a direction you want to pursue?

**Comment by ts-thomas** [comment]
I will solve the conflicts later today.

**Comment by ts-thomas** [comment]
We do need further investigation. The lines like `const src = process.argv[2];` has dropped, so that does not work via command line. The probably fastest solution is that I split CLI logic and provide an exported compile function. I will look for other changes you made and will take them also.

**Comment by ts-thomas** [comment]
I'm done. You can import the `compile` as node module as described here: https://github.com/nextapps-de/mikado-compile#node-module
... or use the CLI
I will close this PR

**Pull request closed without merging**
